import React from 'react';

const Home = () => {
  return (
    <div className="p-10 md:pt-5 pt-20">
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>
      <p>lorem ipsum dolor sit amet, consectet</p>

    </div>
  )
}

export default Home;